### ISSUE TITLE
[June] Issues Master List

### ISSUE THREAD

**Issue by shreythecray** [bitprj/people#149]
# First brought up in _June_
> Only mark off an issue when all related issues are complete **AND** when all related parties agree that issue is resolved
> DRI of this issue: **Director of People Department**

#### Template:
> **Copy this template** and submit your concern in the comments section below:
```
- [ ] Concern
  - Client:
  - Description:
  - Related issues: #
---
```

# 🔥 only directors edit this issue

## Directors:
> Issues brought up by directors/involving directors at highest level

## Managers:
> Issues brought up by managers/involving manager at highest level

## Project Leads:
> Issues brought up by leads/involving leads at highest level

## Members:
> Issues brought up by members/involving members at highest level

**Comment by shreythecray** [comment]
- [ ] Policies
  - Client: @shreyagupta98 
  - Description: We need clear and updated policies for all departments and teams and we need an infrastructure to start, enforce, and maintain it overtime.
  - Related issues: none yet
---
- [ ] Values/mission
  - Client: @shreyagupta98 
  - Description: We need clear and updated values/mission statement for entire organization and policies that match the values
  - Related issues: none yet

**Comment by beccatran** [comment]
- [x] Workflow and task assignments 
  - Client: @beccatran 
  - Description: 
- There has been a lot of feedback regarding overwhelmed members with extra (random task assigned throughout the week) tasks. Although the tasks are clear to do, they have been assigned it randomly during the week. By adding random tasks to members it creates a sense of unstructured responsibilities for each position. 
    - Maintain clear responsibilities 
    - Following OKR timeline protocol to assign tasks. This will allow members to effective plan out their [tasks](https://github.com/bitprj/onboarding/blob/master/Offboarding/JasmineCheng.md)
      - "i feel like it would be good if we could like have it assigned like at a certain time per week???"- Anonymous 
      - More [feedback](https://github.com/bitprj/onboarding/blob/master/Offboarding/RyanKuang.md) about needing more time to plan. 
    - More realistic timelines 
  - In general some members think it is too much [time commitment](https://github.com/bitprj/onboarding/blob/master/Offboarding/NicholasTom.md)
  - "Tasks are often asked ASAP"- Anonymous 
____________________
- [x] Communication 
  - Client: @beccatran 
  - Description: 
- More [opinions](https://github.com/bitprj/onboarding/blob/master/Offboarding/JasmineCheng.md) need to be heard. Have other lead the conversation rather than just the leadership team. 
  - More trust needed in leadership
___________________________
- [x] Club and Culture Structure  
  - Client: @beccatran 
  - Description: 
- Growing is a good idea, but foundations need to be in place before having the mission of growing (values, mission, work structure, etc)
    - " i don't know how the organization will remain sustainable, especially when you grow in size, when there are not systems in place to manage a diverse body of people and communicate effectively"- Anonymous 
- More member appreciation 
- Controlling the amount of Change Management 
   - "There is a decentralized network of communication from the executive team to the managers. The project scopes are never set in stone and constantly changing, often rendering member’s work useless. This does not help the atmosphere of the team at all. Moreover, such changes are not communicated at all. I feel like the executive level makes decisions and never communicates it to the members, while so they demand others to communicate with them—a hypocritical ask. I strongly believe the executive team needs to clarify exactly what their product is before starting the project. It had caused people like me to complete my work only to realize I wasted my time because it wasn’t even used. All in all, fix Bit Project’s product and communicate well while realizing the executive team is currently being hypocritical. They ask others to do things they are not."- Anonymous 


- Related issues: #
